export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART";
export const INCREASE_QUANTITY_SUCCESS = "INCREASE_QUANTITY_SUCCESS";
export const DECREASE_QUANTITY_SUCCESS = "DECREASE_QUANTITY_SUCCESS";
